#requires -Version 7.0
<#
.SYNOPSIS
Deterministic staleness gate for the generated human architecture document.

.DESCRIPTION
The architecture human doc (docs/architecture-notes/architecture.human.md) is a DERIVED artifact
regenerated from the contract sources by New-ArchHumanDoc.ps1. That generator embeds the canonical
contract-sources digest in an `arch-contracts-sha256` marker. This gate recomputes the digest from
the current contract sources (schemas/) via the SAME canonical helper (Get-ArchContractsHash.ps1)
and compares it to the embedded marker:

  * markers match     -> doc is fresh (pass).
  * markers differ    -> a contract was added / removed / edited without regenerating the doc, so it
                         is stale (fail). Run the architecture-notes update flow (/uan) to regen.
  * doc absent        -> the architecture-notes tier is not seeded in this repo (skip / pass).

The doc's mere existence anchors the check — NOT the presence of schemas/, because a repo may keep
an unrelated schemas/ directory (skalary itself does). No architecture human doc means there is
nothing to keep fresh, so the gate is a clean no-op there.

Emits a result object { Status; DocPath; Expected; Actual; Message } for in-process callers (evals),
and exits non-zero on drift / corruption so it doubles as a CLI / CI gate.
#>
[CmdletBinding()]
param(
    # Repository (or worktree) root holding schemas/ and docs/architecture-notes/.
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path,

    # Explicit path to the canonical Get-ArchContractsHash.ps1 helper. Auto-resolved when omitted.
    [string]$HashScriptPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $RepoRoot -PathType Container)) {
    throw "RepoRoot not found or not a directory: $RepoRoot"
}
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path

$notesDir = Join-Path $RepoRoot 'docs/architecture-notes'
$docPath = Join-Path $notesDir 'architecture.human.md'
$markerPattern = '<!--\s*arch-contracts-sha256:\s*(?<digest>[^>\s]+)\s*-->'

function New-FreshnessResult {
    param(
        [Parameter(Mandatory)][ValidateSet('pass', 'skip', 'fail')][string]$Status,
        [Parameter(Mandatory)][string]$Message,
        [string]$Expected,
        [string]$Actual
    )
    [pscustomobject]@{
        Status   = $Status
        DocPath  = $docPath
        Expected = $Expected
        Actual   = $Actual
        Message  = $Message
    }
}

# --- No-op when the architecture-notes tier is not seeded ---------------------------------------
if (-not (Test-Path -LiteralPath $docPath -PathType Leaf)) {
    $rel = [System.IO.Path]::GetRelativePath($RepoRoot, $docPath)
    $result = New-FreshnessResult -Status 'skip' -Message "Architecture-notes tier not seeded (no $rel); nothing to check."
    $result
    Write-Host "[arch-doc-freshness] SKIP: architecture-notes tier not seeded."
    exit 0
}

# --- Resolve the canonical hash helper (single source of truth shared with the generator) --------
if (-not $HashScriptPath) {
    # The helper may live either in the gate's own repo (skalary source / dogfood) or, when this
    # gate is bundled into a consumer repo, alongside the installed plugin under that repo root.
    $gateRepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path
    $relCandidates = @(
        'plugins/architecture-notes/scripts/Get-ArchContractsHash.ps1',
        '.github/skills/architecture-notes/scripts/Get-ArchContractsHash.ps1'
    )
    $roots = @($gateRepoRoot, $RepoRoot) | Select-Object -Unique
    # gateRepoRoot is searched first so an explicit -RepoRoot pointing at a FOREIGN repo still uses
    # this gate's own helper. Generator and gate must share one Get-ArchContractsHash version, so this
    # gate is only version-safe for a doc generated by the same repo/checkout it ships in; auditing a
    # foreign repo's doc assumes that repo pins a compatible digest algorithm (pass -HashScriptPath to
    # bind that repo's helper explicitly when they can skew).
    foreach ($root in $roots) {
        foreach ($rel in $relCandidates) {
            $candidate = Join-Path $root $rel
            if (Test-Path -LiteralPath $candidate -PathType Leaf) {
                $HashScriptPath = (Resolve-Path -LiteralPath $candidate).Path
                break
            }
        }
        if ($HashScriptPath) { break }
    }
}
if (-not $HashScriptPath -or -not (Test-Path -LiteralPath $HashScriptPath -PathType Leaf)) {
    throw "Could not locate Get-ArchContractsHash.ps1 (the canonical digest helper); pass -HashScriptPath explicitly."
}
. $HashScriptPath  # dot-source Get-ArchContractsHash

# --- Extract the embedded digest from the doc ---------------------------------------------------
# A staleness gate must never false-green: read the marker defensively. Require EXACTLY ONE marker
# holding a canonical 64-hex digest. Zero markers, a duplicate/stray marker (e.g. copy-pasted into
# the hand-authored narrative), or a malformed digest all fail loud rather than letting a non-
# canonical value silently satisfy the comparison.
$doc = [System.IO.File]::ReadAllText($docPath)
$markerMatches = @([regex]::Matches($doc, $markerPattern))
if ($markerMatches.Count -eq 0) {
    $result = New-FreshnessResult -Status 'fail' -Message "Human doc is missing the arch-contracts-sha256 marker; regenerate it with New-ArchHumanDoc.ps1 (/uan)."
    $result
    [Console]::Error.WriteLine("[arch-doc-freshness] FAIL: $($result.Message)")
    exit 1
}
if ($markerMatches.Count -gt 1) {
    $result = New-FreshnessResult -Status 'fail' -Message "Human doc has $($markerMatches.Count) arch-contracts-sha256 markers; it is corrupt (a stray/duplicate marker can mask staleness). Regenerate it with New-ArchHumanDoc.ps1 (/uan)."
    $result
    [Console]::Error.WriteLine("[arch-doc-freshness] FAIL: $($result.Message)")
    exit 1
}
$embedded = $markerMatches[0].Groups['digest'].Value
if ($embedded -notmatch '^[0-9a-f]{64}$') {
    $result = New-FreshnessResult -Status 'fail' -Actual $embedded -Message "Human doc arch-contracts-sha256 marker is not a canonical SHA-256 digest ('$embedded'); regenerate it with New-ArchHumanDoc.ps1 (/uan)."
    $result
    [Console]::Error.WriteLine("[arch-doc-freshness] FAIL: $($result.Message)")
    exit 1
}

# --- Recompute the current digest and compare ---------------------------------------------------
# Compute the schemas path AFTER dot-sourcing: the helper's own `$SchemasDir` param would otherwise
# clobber a pre-set local (PowerShell variable names are case-insensitive).
$contractsDir = Join-Path $RepoRoot 'schemas/architecture'
$current = (Get-ArchContractsHash -SchemasDir $contractsDir).Digest

if ([string]::Equals($embedded, $current, [System.StringComparison]::Ordinal)) {
    $result = New-FreshnessResult -Status 'pass' -Message 'Human architecture doc is in sync with the contract sources.' -Expected $current -Actual $embedded
    $result
    Write-Host "[arch-doc-freshness] PASS: doc digest matches contract sources ($current)."
    exit 0
}

$result = New-FreshnessResult -Status 'fail' -Expected $current -Actual $embedded `
    -Message "Human architecture doc is stale: embedded digest '$embedded' != current contract digest '$current'. A contract was added, removed, or edited without regenerating the doc. Run the architecture-notes update flow (/uan) / New-ArchHumanDoc.ps1 and commit the refreshed doc."
$result
[Console]::Error.WriteLine("[arch-doc-freshness] FAIL: $($result.Message)")
exit 1
